### ISSUE TITLE
Too many tiles for Inventory Resource's Summary card

### ISSUE THREAD

**Issue by chiatt** [fargeo/afrh#26]
The summary card in the inventory resource model has a cardinality of 1. However, for many instances there are multiple tiles. These need to be consolidated into a single tile.  See this resource instance as an example: http://localhost:8000/resource/b98d9b6b-4a70-4d1a-88b2-3aafa5fcd46f

**Comment by ryan86** [comment]
Scripted the collapsing of multiple Summary cards into one.

**Comment by mradamcox** [comment]
Seems to be properly handled.
