### ISSUE TITLE
To many tiles for Inventory Resource's Spatial Location card

### ISSUE THREAD

**Issue by chiatt** [fargeo/afrh#27]
The Spatial Location card in the Inventory Resource model has a cardinality of 1. However, for many instances there are multiple tiles. These need to be consolidated into a single tile. See this resource instance as an example: http://localhost:8000/resource/b98d9b6b-4a70-4d1a-88b2-3aafa5fcd46f

**Comment by ryan86** [comment]
Scripted the collapse of multiple Spatial Location tiles into one.

**Comment by mradamcox** [comment]
Fixed in business data.
