### ISSUE TITLE
Too many tiles saved to the Evaluation Card in the Inventory Resource model

### ISSUE THREAD

**Issue by chiatt** [fargeo/afrh#28]
The Evaluation card in the Inventory Resource model has a cardinality of 1. However, for many instances there are multiple tiles. These need to be consolidated into a single tile. See this resource instance as an example: http://localhost:8000/resource/b98d9b6b-4a70-4d1a-88b2-3aafa5fcd46f

**Comment by ryan86** [comment]
Scripted a solution to recreate Evaluation Tiles from exported v3 data
