### ISSUE TITLE
Master Plan Zone's Spatial Location Card has too many tiles

### ISSUE THREAD

**Issue by chiatt** [fargeo/afrh#30]
The issue may only be with this resource instance:
http://localhost:8000/resource/9fedd064-27a5-46cd-87b0-e021b1b2ae97#

This resource Master Plan Zone has 2 features. Could it be that this should be divided into two different instances or should both features be moved into the same feature collection in one tile.

**Comment by ryan86** [comment]
Manually collapsed many geometries tiles into one geom collection

**Comment by mradamcox** [comment]
Fixed in business data.
