### ISSUE TITLE
Too many tiles for the Information Resource's Summary Card

### ISSUE THREAD

**Issue by chiatt** [fargeo/afrh#32]
The Summary Card in the Information Resource model has a cardinality of 1. However, for many instances there are multiple tiles. These need to be consolidated into a single tile. See this resource instance as an example: http://localhost:8000/resource/74e60237-04bf-4428-86c9-6c2e2a11177f

**Comment by ryan86** [comment]
Scripted the collapse of many Summary tiles into one.
